name: Android CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.7
      - name: Generate Gradle Wrapper (if missing)
        run: gradle wrapper --gradle-version 8.7
      - name: Build Debug APK
        env:
          ORG_GRADLE_PROJECT_android.experimental.enableSdkDownload: "true"
        run: ./gradlew --no-daemon clean assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: z9turbo-apk
          path: app/build/outputs/apk/debug/*.apk
